### ISSUE TITLE
Instructions Missing Details

### ISSUE THREAD

**Issue by KitchM** [aktau/hhpc#10]
Your instructions include the line:
$ git clone ...

I do not know what the "..." means.  Could you please explain?

Thanks.

**Comment by theno** [comment]
The line should be the command to clone this repo:

    $ git clone https://github.com/aktau/hhpc.git

or 

    $ git clone git@github.com:aktau/hhpc.git

The "..." is the URL of the repo. You can find the clone URL in the right sidebar of the repository page.
More info about cloning repos from github: https://help.github.com/articles/cloning-a-repository/

**Comment by aktau** [comment]
Thanks for helping this user out @theno. The reason I used dots is because I don't know if the repository will get moved one day and I don't want the README to become out of date because of that.
