### ISSUE TITLE
No explanation: when does it hide/unhide?

### ISSUE THREAD

**Issue by mvdw** [aktau/hhpc#12]
Can you please explain what are the basic conditions for hiding or unhiding the mouse cursor?

**Comment by chrsw** [comment]
I think some more explanation of what this program is actually doing would be useful. What do you mean by "conditions"?
From what I can tell, someone correct me if I'm wrong, hhpc sets up all the X stuff to get this working, sleeps for a 1 second (by default), checks to see if there's been a mouse event reported by X. If there has been a mouse event, nothing happens to the cursor. If there hasn't been a mouse event hhpc hides the cursor. I might have oversimplified things a bit here but that's my take.

**Comment by mvdw** [comment]
OK, thanks for the explanation. It is clear now.

Understanding your "readme.md" is quite hard if you do not know what "hhp from xmonad-utils" is.
IMHO, you better write for a reader who looks for the functionality, not for someone who wants to upgrade from hhp.

I just installed hhpc, it works, so far I like it! Thanks.

**Comment by chrsw** [comment]
I'm not the author, so take what I said with a grain of salt because it's only my guess. I'm just someone who stumbled across this little utility and found it useful as well. And I agree, there should be a clearer explanation of what's going on here.

**Comment by aktau** [comment]
I'm sorry for that. As it happens so often, I just made this because `hhp` didn't work properly for me and thus advertised it as a "bugfix" on top of this tiny program. I'll see if I can clarify in the README.

**Comment by aktau** [comment]
Hopefully the README is a bit more helpful now. I put it together by looking at the code for a few seconds again (it's been quite some time since I looked at it). If anything's wrong or unclear, feel free to open the issue again.

**Comment by mvdw** [comment]
Much better.
Thanks!
